version: '3'
services:
  maxacraft-database:
    image: postgres
    ports:
      - "3306:5432"
    restart: unless-stopped
    volumes:
      - ./postgresql:/var/lib/postgresql
    environment:
      NODE_ENV: production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mxj3QKB_dzc0rna6zha
      POSTGRES_DB: postgres
